### PR TITLE
Add custom blog plugin

### LINKED ISSUE #285: Convert news to single source, i.e. get rid of the manually maintained copy

### PR DESCRIPTION
**Pull request by TheZoker**
We add a custom blog plugin, which allows to load the recent blog posts on the home page.
This PR is based upon this post here:
https://github.com/facebook/docusaurus/issues/4138#issuecomment-1703083513

This PR also removes all the twitter references. 

Closes #285

### CODE REVIEW

**Review by lucas-koehler — COMMENTED** [review]
Hi @TheZoker , thanks for the PR. The new blog integration seems to work well :) Just one question: Why was `content/pages/index.js` moved to `src/components/home/index.js`?

**Comment by TheZoker** [comment]
Thanks for the review!

It's necessary, because otherwise I cannot use it here (according to the docusaurus devs):
https://github.com/TheZoker/jsonforms2-website/blob/custom-blog-plugin/plugins/custom-blog-plugin.js#L52

**Comment by lucas-koehler** [comment]
> Thanks for the review!
> 
> It's necessary, because otherwise I cannot use it here (according to the docusaurus devs): https://github.com/TheZoker/jsonforms2-website/blob/custom-blog-plugin/plugins/custom-blog-plugin.js#L52

@TheZoker I see. But could you not just leave the home.js where it is and adapt the path at your referenced location to `@site/content/pages/index.js`? Or does this not work?

**Comment by TheZoker** [comment]
Yes exactly. I tried it and this is the error I got:
```
Unexpected: no Docusaurus route context found
```

So it seems the file needs to be moved for this to work

**Review by lucas-koehler — APPROVED** [review]
@TheZoker I see. Thanks for clarifying. Then this is fine for me :)

**Pull request merged**
