### PR TITLE
Switch to docusaurus

### LINKED ISSUE #84: Update to Docz 2
- The site needs some overhaul regarding the theme
- The embedded examples work but throw errors when switching tabs

### PR DESCRIPTION
**Pull request by TheZoker**
Switch from docz to [docusaurus 2](https://v2.docusaurus.io/)

Closes #84

Currently not working:

- [ ] Blog on front page (see https://github.com/facebook/docusaurus/discussions/4443)

### CODE REVIEW

**Review by sdirix — COMMENTED** [review]
I already like it very much! It's much faster than the old site and better looking ! Great work!

Some things I noticed:
 - I would prefer `npm` over `yarn`, in general we only use `yarn` when necessary.
 - Can we modify the text on the landing page on green background to always be black? Or maybe change the font in general. When it's white it looks somewhat weak.
 - The forms are pretty dense. Can you modify them similar to the React seed (see the theme there) so they take more space?
 - The large architecture diagram is missing in the docs
 - The Create a JSON Forms app tutorial is not properly intended in section 1.
 - The React integration note can also just be an info. The red is too hard ;)

Let me know when I shall do a detailed review ;)

**Review by sdirix — COMMENTED** [review]
- Remove dark theme for now
 - Make architecture picture larger and above the text
 - Consistent white color for button on landing page
 - Vertical scrollbar on all pages

**Comment by eneufeld** [comment]
Site looks great.
I don't like the green color though.

Actual things:
- Examples -> Array
  - add a sentence when the table is used, when a different renderer is used, maybe add the second case on the page?
- Examples -> Categorization
  - Address Tab is shown but the text tells me to check the `Provide Address` box to see it :confused: 
  - The different variant should have a heading, the normal text does not separate them well enough
- Examples -> Control
  - The options part is undocumented, where can I use which option? Can I look up available options?
- Examples
  The overall order of the examples is a bit random. I suggest to sort them.
- Docs -> Renderer sets
  Vue set is missing or is it not published?
- Docs -> Getting started
  List Vue seed 

I personally find the footer to high for 5 entries (of which one is already in the header).
I would love to see a link to spectrum or the successor tool somewhere.
The FAQ outline does not highlight the last entry even if you click on it.
 
 **None** of the issues mentioned above are critical. Page worked well for me.

**Comment by TheZoker** [comment]
Thanks for the feedback!

- Is there a typical jsonforms color we can use instead of the green (which is the default for docusaurus)?
- I already asked in the docusaurus repo, if there is a way to use a smaller footer (similar to the current jsonforms page). But if we want to add more links to the footer, I guess we can keep the large footer and just use the space to promote more links (like spectrum). Are there more links that should be in the footer? 
image
- The content of the docs is currently unchanged, I only copied the content of the old page (but it would be a good followup PR to clear some things there)
- The TOC (not only on the FAQ page) is based on the current viewing position. Since the last item so nearly at the bottom, it never comes into the "view of the visitor" (which is typically assumed to be at the top corner of the screen):
Screenshot_2021 03 23_18h42m18s_003_
Screenshot_2021 03 23_18h42m12s_002_
Only when the title is right on the top, the TOC element get highlighted. Since this is the default docusaurus behavior, there is nothing much we can do about it (except for implementing a custom TOC)

**Comment by sdirix** [comment]
Thanks @eneufeld. I'll create follow ups for all issues you mentioned here, except for the green color. I agree that we should change that and ideally before release.

@TheZoker I like the community links!

@TheZoker Instead of the green background we can just use white. Then it has the same design as the current JSON Forms Website. Actually as the current one is not too bad, maybe you can just replicate it including font sizes, logo size, bold sections and colors.

**Review by sdirix — APPROVED** [review]
Very nice!

**Pull request merged**
