### PR TITLE
Incorrect example

### PR DESCRIPTION
**Pull request by waypar**
Hi,
I tried copy/pasting this example, it didn't work. I think maybe the attached diff is how it is supposed to work?

### CODE REVIEW

**Comment by sdirix** [comment]
Hi! Thanks for the contribution!

Sadly the suggestion is incorrect. The `translator` expected by JSON Forms is really only the translate function itself, not a translation factory.

Of course you can use such a factory for providing up to date translate functions to JSON Forms whenever the locale changes, but you don't hand over the factory directly.

**Review by sdirix — COMMENTED** [review]
Hi! Thanks for the contribution! :heart: 

Yes you're right! The way the example code is set up `translator` should be a locale-aware factory!

The improvement is already great, but could we then also improve the naming? i.e. instead of `translator` the function should be called `createTranslate` or `createTranslator`, then it's more obvious what it's doing.

---
fyi: I deleted my old comment where I reviewed this change without the surrounding context

**Comment by waypar** [comment]
Done

**Review by sdirix — APPROVED** [review]
Thanks!

**Pull request merged**
