### PR TITLE
Add ListWithDetail example

### LINKED ISSUE #54: Add ListWithDetail example

### PR DESCRIPTION
**Pull request by TheZoker**
Closes #54

### CODE REVIEW

**Review by sdirix — CHANGES_REQUESTED** [review]
It works! Let us polish a bit:

- Add proper `title` attributes to the schema so the form labels look good
- Show First name in List instead of a number

**Review by sdirix — CHANGES_REQUESTED** [review]
Needs to be rebased

**Review by sdirix — CHANGES_REQUESTED** [review]
We should remove the `definitions` as they are unused here.

**Comment by sdirix** [comment]
Please rebase on latest master and rename example to Master Detail

**Comment by TheZoker** [comment]
Done ✔️

**Review by sdirix — CHANGES_REQUESTED** [review]
Talked with the team, we need to rename back to `ListWithDetail` / `List with Detail` ;) Sorry for the inconvenience. Please also rename in the renderer set table.

**Review by sdirix — CHANGES_REQUESTED** [review]
The example doesn't work :/

**Review by sdirix — APPROVED** [review]
LGTM

**Pull request merged**
